name = "github-proxy"
compatibility_date = "2025-02-21"

main = "src/index.js"

workers_dev = true
preview_urls = false
minify = true
upload_source_maps = false
keep_vars = true

[vars]
HomeMode = ""
HomePage = ""

[dev]
ip = "0.0.0.0"
port = 8787